# Generated by Django 2.2 on 2021-05-22 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shows_app', '0002_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='made',
            field=models.ManyToManyField(related_name='made_movies', to='shows_app.User'),
        ),
        migrations.AddField(
            model_name='show',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shows', to='shows_app.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='confirm_password',
            field=models.CharField(max_length=255),
        ),
    ]
